---
retweet:
  from:
    - screen_name: C5_CDMX
      id: '195951901'
    - screen_name: SPCCDMX
      id: '109157742'
    - screen_name: CFEmx
      id: '310535100'
    - screen_name: CFE_Sureste
      id: '308591430'
    - screen_name: CFE_ValleMex
      id: '308626627'
    - screen_name: SSP_CDMX
      id: '62844209'
    - screen_name: conagua_mx
      id: '162074535'
    - screen_name: conaguaChiapas
      id: '569320083'
    - screen_name: ConaguaPuebla
      id: '333699671'
    - screen_name: Conagua_Oaxaca
      id: '331895341'
    - screen_name: Tu_IMSS
      id: '69034805'
    - screen_name: ISSSTE_mx
      id: '1183751622'
    - screen_name: Imss_Pue
      id: '2216210492'
    - screen_name: IMSSedomexote
      id: '831964952273514497'
    - screen_name: IMSS_Oaxaca
      id: '2196395749'
    - screen_name: locatel_mx
      id: '730996422'
    - screen_name: SSalud_mx
      id: '132225222'
    - screen_name: Salud_Puebla
      id: '827156724591124480'
